# Use Nginx as the base image
FROM nginx:alpine

# Remove default page
RUN rm -rf /usr/share/nginx/html/*

# Copy your HTML file into the container
COPY simple.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Nginx already runs as default CMD
