name: Deploy HTML Site to GitHub Pages

on:
  push:
    branches:
      - main  # or "master", depending on your branch name

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .  # This uploads your HTML file

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
